In [1]:
documents = [
    "This is a list which containing sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings.",
    "Understanding document structure aids in keyword extraction.",
    "Efficient keyword extraction enhances search accuracy.",
    "Semantic similarity improves document retrieval performance.",
    "Machine learning algorithms can optimize keyword extraction methods."
]

In [2]:
!pip install sentence_transformers

In [3]:
from sentence_transformers import SentenceTransformer

The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.


In [4]:
model_name = 'sentence-transformers/paraphrase-xlm-r-multilingual-v1'

In [5]:
model = SentenceTransformer(model_name)

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

c:\Users\parth\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:140: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\parth\.cache\huggingface\hub\models--sentence-transformers--paraphrase-xlm-r-multilingual-v1. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.78k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/718 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/550 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

1_Pooling%2Fconfig.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [6]:
documents

['This is a list which containing sample documents.',
 'Keywords are important for keyword-based search.',
 'Document analysis involves extracting keywords.',
 'Keyword-based search relies on sparse embeddings.',
 'Understanding document structure aids in keyword extraction.',
 'Efficient keyword extraction enhances search accuracy.',
 'Semantic similarity improves document retrieval performance.',
 'Machine learning algorithms can optimize keyword extraction methods.']

In [7]:
len(documents)

8

In [8]:
document_embeddings = model.encode(documents)

In [9]:
len(document_embeddings)

8

In [10]:
len(document_embeddings[0])

768

In [11]:
for i, embedding in enumerate(document_embeddings):
    print(f"Document {i+1} embedding: {embedding}")

Document 1 embedding: [ 0.1089468   0.07812066  0.11626569 -0.319125    0.46890232  0.43514383
  0.01453742  0.44238767  0.29716396 -0.18982702  0.07389062 -0.27864903
  0.2133816  -0.12077009  0.17891707 -0.00789893  0.04754857 -0.18204558
  0.3422711  -0.06994266 -0.14288734  0.5714126  -0.11153235 -0.17895402
  0.01523128  0.26105705 -0.2055583   0.05203113 -0.02810769  0.2387324
  0.01206973  0.04404931  0.02242315 -0.13895167 -0.74100375  0.25601012
  0.08149683  0.18820493 -0.41237697  0.11368614  0.28121158  0.05860885
 -0.17318778  0.33549133  0.21803679 -0.05090715 -0.05457796 -0.87384796
 -0.24082261  0.32006976  0.44761658  0.06347828  0.53574854  0.16607258
 -0.33196995  0.33393642  0.2861591  -0.5419567  -0.2713242   0.24881153
 -0.2391938  -0.46926305  0.13836576  0.3784289  -0.01304437  0.01990602
  0.32365084  0.45857537  0.07600269  0.25299588 -0.4293894   0.1005192
 -0.33042598 -0.6987646   0.01035898  0.05666557  0.14731242 -0.4708235
  0.08063991  0.33870462 -0.2727

In [12]:
documents

['This is a list which containing sample documents.',
 'Keywords are important for keyword-based search.',
 'Document analysis involves extracting keywords.',
 'Keyword-based search relies on sparse embeddings.',
 'Understanding document structure aids in keyword extraction.',
 'Efficient keyword extraction enhances search accuracy.',
 'Semantic similarity improves document retrieval performance.',
 'Machine learning algorithms can optimize keyword extraction methods.']

In [13]:
query = "Natural language processing techniques enhance keyword extraction efficiency."

In [14]:
query_embedding = model.encode(query)

In [15]:
print("Query embedding:", query_embedding)

Query embedding: [ 3.42821062e-01  3.26170385e-01  7.73261068e-03  1.60758514e-02
  2.38516666e-02 -2.52880663e-01  8.15468580e-02  1.37177333e-01
  3.33291858e-01  3.65742818e-02 -9.28223878e-02 -3.43725681e-01
  7.12015703e-02  9.48833764e-01 -9.41288918e-02 -7.96414077e-01
 -3.20592076e-01 -2.67564565e-01  2.08664283e-01  7.99598843e-02
  7.93335307e-03 -5.22297248e-02 -1.00512788e-01 -2.04229966e-01
  2.19562680e-01  7.67739341e-02  1.25881538e-01  2.90843874e-01
 -4.99191135e-01  2.27709755e-01 -1.94742575e-01  7.21395537e-02
 -4.56501637e-03  1.21945590e-01 -1.46225810e-01 -9.64745283e-02
  1.02258295e-01 -2.04421118e-01 -3.95657718e-01  7.32252896e-02
  1.10104270e-01  4.84611213e-01  1.04519263e-01  3.86131793e-01
 -1.68697298e-01 -2.11251184e-01 -6.38036430e-01 -4.32641625e-01
  2.74459243e-01  9.64054689e-02 -1.30053580e-01  5.76567017e-02
  8.07962939e-02  6.48147985e-02 -2.14182865e-03  2.29773745e-01
 -6.66054189e-02  3.07675481e-01  2.11779565e-01 -1.57844394e-01
  9.7885

In [16]:
len(query_embedding)

768

In [17]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
similarities = cosine_similarity(np.array([query_embedding]), document_embeddings)

In [19]:
similarities

array([[0.16948152, 0.45802277, 0.5675694 , 0.44123292, 0.6316117 ,
        0.7521413 , 0.55035186, 0.74481654]], dtype=float32)

In [20]:
most_similar_index = np.argmax(similarities)

In [21]:
most_similar_index

5

In [22]:
most_similar_document = documents[most_similar_index]

In [23]:
most_similar_document

'Efficient keyword extraction enhances search accuracy.'

In [24]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [25]:
similarity_score = similarities[0][most_similar_index]

In [26]:
similarity_score

0.7521413

In [27]:
sorted_indices = np.argsort(similarities[0])[::-1]

In [28]:
sorted_indices

array([5, 7, 4, 2, 6, 1, 3, 0], dtype=int64)

In [29]:
ranked_documents = [(documents[i], similarities[0][i]) for i in sorted_indices]

In [30]:
ranked_documents

[('Efficient keyword extraction enhances search accuracy.', 0.7521413),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.74481654),
 ('Understanding document structure aids in keyword extraction.', 0.6316117),
 ('Document analysis involves extracting keywords.', 0.5675694),
 ('Semantic similarity improves document retrieval performance.', 0.55035186),
 ('Keywords are important for keyword-based search.', 0.45802277),
 ('Keyword-based search relies on sparse embeddings.', 0.44123292),
 ('This is a list which containing sample documents.', 0.16948152)]

In [31]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [32]:
print("Ranked Documents:")
for rank, (document, similarity) in enumerate(ranked_documents, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Ranked Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.7521412968635559
Rank 2: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.7448165416717529
Rank 3: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.631611704826355
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.567569375038147
Rank 5: Document - 'Semantic similarity improves document retrieval performance.', Similarity Score - 0.5503518581390381
Rank 6: Document - 'Keywords are important for keyword-based search.', Similarity Score - 0.4580227732658386
Rank 7: Document - 'Keyword-based search relies on sparse embeddings.', Similarity Score - 0.44123291969299316
Rank 8: Document - 'This is a list which containing sample documents.', Similarity Score - 0.16948151588439941


In [33]:
print("Top 4 Documents:")
for rank, (document, similarity) in enumerate(ranked_documents[:4], start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Top 4 Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.7521412968635559
Rank 2: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.7448165416717529
Rank 3: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.631611704826355
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.567569375038147


In [34]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [35]:
!pip install rank_bm25

  Using cached rank_bm25-0.2.2-py3-none-any.whl.metadata (3.2 kB)
Using cached rank_bm25-0.2.2-py3-none-any.whl (8.6 kB)


In [36]:
from rank_bm25 import BM25Okapi

In [45]:
top_4_documents = [doc[0] for doc in ranked_documents[:4]]

In [46]:
top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [47]:
tokenized_top_4_documents = [doc.split() for doc in top_4_documents]

In [48]:
tokenized_top_4_documents

[['Efficient', 'keyword', 'extraction', 'enhances', 'search', 'accuracy.'],
 ['Machine',
  'learning',
  'algorithms',
  'can',
  'optimize',
  'keyword',
  'extraction',
  'methods.'],
 ['Understanding',
  'document',
  'structure',
  'aids',
  'in',
  'keyword',
  'extraction.'],
 ['Document', 'analysis', 'involves', 'extracting', 'keywords.']]

In [49]:
tokenized_query = query.split()

In [50]:
tokenized_query

['Natural',
 'language',
 'processing',
 'techniques',
 'enhance',
 'keyword',
 'extraction',
 'efficiency.']

In [51]:
bm25=BM25Okapi(tokenized_top_4_documents)

In [52]:
bm25

In [53]:
bm25_scores = bm25.get_scores(tokenized_query)

In [54]:
bm25_scores

array([0.1907998 , 0.16686672, 0.17803252, 0.        ])

In [55]:
sorted_indices2 = np.argsort(bm25_scores)[::-1]

In [56]:
sorted_indices2

array([0, 2, 1, 3], dtype=int64)

In [57]:
top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [58]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [59]:
reranked_documents = [(top_4_documents[i], bm25_scores[i]) for i in sorted_indices2]

In [60]:
reranked_documents

[('Efficient keyword extraction enhances search accuracy.',
  0.19079979534096053),
 ('Understanding document structure aids in keyword extraction.',
  0.1780325227902643),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.1668667199671815),
 ('Document analysis involves extracting keywords.', 0.0)]

In [61]:
print("Rerank of top 4 Documents:")
for rank, (document, similarity) in enumerate(reranked_documents, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Rerank of top 4 Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.19079979534096053
Rank 2: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.1780325227902643
Rank 3: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.1668667199671815
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.0


In [62]:
ranked_documents[:4]

[('Efficient keyword extraction enhances search accuracy.', 0.7521413),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.74481654),
 ('Understanding document structure aids in keyword extraction.', 0.6316117),
 ('Document analysis involves extracting keywords.', 0.5675694)]

# Cross-Encoder

In [63]:
from sentence_transformers import CrossEncoder

In [64]:
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

c:\Users\parth\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:140: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\parth\.cache\huggingface\hub\models--cross-encoder--ms-marco-MiniLM-L-6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [65]:
top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [66]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [67]:
pairs = []
for doc in top_4_documents:
    pairs.append([query, doc])

In [68]:
pairs

[['Natural language processing techniques enhance keyword extraction efficiency.',
  'Efficient keyword extraction enhances search accuracy.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Machine learning algorithms can optimize keyword extraction methods.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Understanding document structure aids in keyword extraction.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Document analysis involves extracting keywords.']]

In [69]:
scores = cross_encoder.predict(pairs)
scores

array([ 3.137872 ,  0.8421651, -2.919301 , -2.8781886], dtype=float32)

In [70]:
scored_docs = zip(scores, top_4_documents)

In [71]:
scored_docs

In [72]:
reranked_document_cross_encoder = sorted(scored_docs, reverse=True)

In [73]:
reranked_document_cross_encoder

[(3.137872, 'Efficient keyword extraction enhances search accuracy.'),
 (0.8421651,
  'Machine learning algorithms can optimize keyword extraction methods.'),
 (-2.8781886, 'Document analysis involves extracting keywords.'),
 (-2.919301, 'Understanding document structure aids in keyword extraction.')]

# BM_25

In [74]:
reranked_documents

[('Efficient keyword extraction enhances search accuracy.',
  0.19079979534096053),
 ('Understanding document structure aids in keyword extraction.',
  0.1780325227902643),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.1668667199671815),
 ('Document analysis involves extracting keywords.', 0.0)]

In [75]:
!pip install cohere

In [76]:
import cohere

In [77]:
co = cohere.Client("cKQkbLuDBesTKAeq7ypT5NWH33Do58FJoD0cX2av")

In [78]:
top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [79]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [80]:
response = co.rerank(
    model="rerank-english-v3.0",
    query="Natural language processing techniques enhance keyword extraction efficiency.",
    documents=top_4_documents,
    return_documents=True
)

In [81]:
print(response)

id='e42de380-647f-4ed6-a3ed-754febc60c62' results=[RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Efficient keyword extraction enhances search accuracy.'), index=0, relevance_score=0.99411184), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Machine learning algorithms can optimize keyword extraction methods.'), index=1, relevance_score=0.9129032), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Understanding document structure aids in keyword extraction.'), index=2, relevance_score=0.32885265), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Document analysis involves extracting keywords.'), index=3, relevance_score=0.02865267)] meta=ApiMeta(api_version=ApiMetaApiVersion(version='1', is_deprecated=None, is_experimental=None), billed_units=ApiMetaBilledUnits(images=None, input_tokens=None, output_tokens=None, search_units=1.0, classifications=None), tokens=None, warnings=None)


In [82]:
response.results[0].document.text

'Efficient keyword extraction enhances search accuracy.'

In [83]:
response.results[0].relevance_score

0.99411184

In [84]:
for i in range(4):
  print(f'text: {response.results[i].document.text} score: {response.results[i].relevance_score}')

text: Efficient keyword extraction enhances search accuracy. score: 0.99411184
text: Machine learning algorithms can optimize keyword extraction methods. score: 0.9129032
text: Understanding document structure aids in keyword extraction. score: 0.32885265
text: Document analysis involves extracting keywords. score: 0.02865267
